#!/usr/bin/env python3

import base64
import sys


if(len(sys.argv) != 3 or sys.argv[1] == "-h"):
    print("Usage: b64 {-e|-d} \"<string>\"\n");
    print("-e -> Encodes the data")
    print("-d -> Decodes the data")
    print("-h -> To show the syntax or semantics")
    exit(-1)


path = sys.argv[0]
option=sys.argv[1]
data = sys.argv[2]

if(option == '-e'):
    print(base64.b64encode(data.encode()).decode())

elif(option == '-d'):
    print(base64.b64decode(data.encode()).decode())

else:
    print("Usage: b64 {-e|-d} [-h] \"<string>\"\n");
    print("-e -> Encodes the data")
    print("-d -> Decodes the data")
    print("-h -> To show the syntax or semantics")
    exit(-1)